name: Release WordPress Plugin

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build --verbose

      - name: Create plugin zip
        run: yarn plugin-zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
          generate_release_notes: true
          make_latest: true
          fail_on_unmatched_files: true
